# Generated by Django 2.2.14 on 2020-08-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_has_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_store',
        ),
    ]
