# Generated by Django 2.2.14 on 2020-08-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_has_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='shopApp.Store'),
        ),
    ]
