# Generated by Django 2.2.14 on 2020-08-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200814_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shopApp.Store'),
        ),
    ]
