# Generated by Django 2.2.14 on 2020-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='USA', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.CharField(default='USA', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='zip_code',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
