# Generated by Django 2.2.14 on 2020-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20200804_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
