# Generated by Django 2.2.14 on 2020-08-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_auto_20200807_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopApp.Store'),
        ),
    ]
