# Generated by Django 2.2.14 on 2020-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_auto_20200810_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
