# Generated by Django 2.2.14 on 2020-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_product_sold_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'parent_category',
                'verbose_name_plural': 'parent_categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
