# Generated by Django 2.2.14 on 2020-08-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_auto_20200829_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(default='1.0.0+1', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parentcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shopApp.ParentCategory'),
        ),
    ]
