# Generated by Django 2.2.14 on 2020-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_auto_20200831_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
