# Generated by Django 2.2 on 2020-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0019_auto_20201124_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
