# Generated by Django 2.2 on 2020-11-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0021_auto_20201124_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='name_cn',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='name_it',
        ),
    ]
