# Generated by Django 2.2 on 2020-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0024_auto_20201124_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_cn',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_it',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
