# Generated by Django 2.2.14 on 2020-08-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
