# Generated by Django 2.2.14 on 2020-08-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200821_1237'),
        ('orders', '0004_auto_20200821_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
