# Generated by Django 2.2.14 on 2020-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='No country configured yet', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='No phone number configured yet', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='No street configured yet', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default='1234'),
        ),
    ]
